import enum

AXIS = enum.Enum("AXIS", ["FREQUENCY", "INTENSITY", "DENSITY"])
FREQUENCY_REGIONS = enum.Enum("FREQUENCY_REGIONS", ["F0", "F1"])
INTENSITY_REGIONS = enum.Enum("INTENSITY_REGIONS", ["G0", "G1"])
DENSITY_REGIONS = enum.Enum("DENSITY_REGIONS", ["D0", "D1"])
DURATION_REGIONS = enum.Enum("DURATION_REGIONS", ["L0", "L1"])


PITCHES_SETS = [{-6, -5, -4, 0, (1, 2), 3}, {-32, -30, 24, 27}]

INTENSITY_SETS = [{-1, 0}, {-2, 2}]

DENSITY_SETS = [{0.7}, {3.0}]

DURATION_SETS = [{0.3}, {1.0}]
